### ISSUE TITLE
Error or timeout when calling SendOutput Files

### ISSUE THREAD

**Issue by hweng** [ucsdlib/billing-circ#6]
Beginning May 24, 2017, when we attempt send the patron billing files to campus, clicking the Send Data button, after acknowledging the requested action, a spinning icon appears and then we get the message, “There was an error or timeout when calling SendOutput Files servlet”.  Campus is apparently receiving the files, but upon investigation the data is not writing to the program’s database and the transaction log is not appearing in the Session module.

Greg

**Comment by hweng** [comment]
@jgorney,
Besides the data type mismatch issue which I talked to you last time. I figured out there are another two issues related to database migration:

1. One is the insert order issue: The PreparedStatement for INVOICEDATE field was placed on the 4th in the order, pstmt.setDate( 4, jsqlD1), but in new migrated postgresSQL PENDING_HISTORY table, this INVOICEDATE column is placed at 20th. 
2. The PENDINGID duplicate key issue. However it is puzzled me that in Oracle it worked fine.

I got the above two issues fixed and tested several loads by using different billing files that they are working fine now.

**Comment by jgorney** [comment]
Oh you got them fixed?  Great!

**Comment by hweng** [comment]
Yup, looks good to me now. I will have Ron to deploy it to production. And let's see how Lilly and Greg's feedback.

**Comment by jgorney** [comment]
Before Ron deploys, I need to apply the database modifications we made, right?  These are the mods I made to test:

alter table transactions alter column itemno type character(10);
alter table transactions alter column userid type character(10);
alter table transactions drop processdate;
alter table invoicenotes drop dateupdated;
drop table errors;
drop table errors_tmp;
drop table transactions_tmp;

**Comment by hweng** [comment]
@jgorney I thought the above operations for TRANSACTIONS table, INVOICENOTES table was already done on production? It has worked fine. Thanks!
The two issues I just mentioned is on PENDING_HISTORY tables which you don't need to do anything for it because I fixed it in the program.

**Comment by jgorney** [comment]
You're right, I did apparently make those two datatype modifications in production.  Sorry!

**Comment by hweng** [comment]
No problem. Thanks @jgorney

**Comment by hweng** [comment]
INC0021895 and INC0026546 have been resolved.
