### ISSUE TITLE
Update config for billingServer on test environment.

### ISSUE THREAD

**Issue by hweng** [ucsdlib/billing-circ#7]
To connect to lib-hydrahead-staging instead of campus server adcom, So that Send Data process in test will send the files to the library sftp server and not adcom, which won't mess up the campus server.

**Comment by jhriv** [comment]
environment.xml has been updated (adcom->lib-hydrahead-staging) and billing-circ has been reloaded

**Comment by gamontoya** [comment]
@hweng Feel free to close this ticket.
